import Board from '@/components/Board/Board';
import RightPanel from '@/components/RightPanel/RightPanel';
import ThemeSelector from '@/components/ThemeSelector/ThemeSelector';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useTheme } from '@/hooks/useTheme';
import { useThemeStyles } from '@/hooks/useThemeStyles';

export default function Home() {
	const [isClient, setIsClient] = useState(false);
	const [score, setScore] = useState(0);
	const [bestScore, setBestScore] = useState(0);
	const { currentTheme, changeTheme } = useTheme();
	const themeStyles = useThemeStyles(currentTheme);

	useEffect(() => {
		setIsClient(true);
		// Загружаем лучший счет из localStorage
		if (typeof window !== 'undefined') {
			const savedBestScore = localStorage.getItem('bestScore');
			if (savedBestScore) {
				setBestScore(parseInt(savedBestScore));
			}
		}
	}, []);

	useEffect(() => {
		// Применяем стили темы к body
		if (typeof document !== 'undefined') {
			document.body.style.background = themeStyles.colors.background;
		}
	}, [themeStyles.colors.background]);

	const handleNewGame = () => {
		setScore(0);
		// Перезагружаем страницу для новой игры
		window.location.reload();
	};

	const handleScoreUpdate = (newScore: number) => {
		setScore(newScore);
		if (newScore > bestScore) {
			setBestScore(newScore);
			if (typeof window !== 'undefined') {
				localStorage.setItem('bestScore', newScore.toString());
			}
		}
	};

	return (
		<>
			<Head>
				<title>2048 NextJs</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Board
					isClient={isClient}
					onScoreUpdate={handleScoreUpdate}
					currentTheme={currentTheme}
				/>
				<RightPanel
					score={score}
					bestScore={bestScore}
					onNewGame={handleNewGame}
					currentTheme={currentTheme}
				/>
				<ThemeSelector
					currentTheme={currentTheme}
					onThemeChange={changeTheme}
				/>
			</main>
		</>
	);
}
