import Board from '@/components/Board/Board';
import RightPanel from '@/components/RightPanel/RightPanel';
import ThemeSelector from '@/components/ThemeSelector/ThemeSelector';
import Head from 'next/head';
import { useState, useEffect, useCallback } from 'react';
import { useTheme } from '@/hooks/useTheme';
import { useThemeStyles } from '@/hooks/useThemeStyles';

export default function Home() {
	const [isClient, setIsClient] = useState(false);
	const [score, setScore] = useState(0);
	const [bestScore, setBestScore] = useState(0);
	const { currentTheme, changeTheme } = useTheme();
	const themeStyles = useThemeStyles(currentTheme);

	useEffect(() => {
		setIsClient(true);
		// Загружаем лучший счет из localStorage
		if (typeof window !== 'undefined') {
			const savedBestScore = localStorage.getItem('bestScore');
			if (savedBestScore) {
				setBestScore(parseInt(savedBestScore));
			}
		}
	}, []);

	useEffect(() => {
		// Применяем стили темы через CSS variables
		if (typeof document !== 'undefined') {
			const root = document.documentElement;
			root.style.setProperty('--app-bg', themeStyles.colors.background);
			root.style.setProperty('--title-color', themeStyles.colors.title);
			root.style.setProperty('--board-bg', themeStyles.colors.board);
			root.style.setProperty('--board-border', themeStyles.colors.boardBorder);
			root.style.setProperty('--empty-tile-bg', themeStyles.colors.emptyTile);
			root.style.setProperty(
				'--empty-tile-border',
				themeStyles.colors.emptyTileBorder
			);
			root.style.setProperty(
				'--score-counter-bg',
				themeStyles.colors.scoreCounter
			);
			root.style.setProperty(
				'--score-counter-border',
				themeStyles.colors.scoreCounterBorder
			);
			root.style.setProperty('--best-score-bg', themeStyles.colors.bestScore);
			root.style.setProperty(
				'--best-score-border',
				themeStyles.colors.bestScoreBorder
			);
			root.style.setProperty(
				'--new-game-button-bg',
				themeStyles.colors.newGameButton
			);
			root.style.setProperty(
				'--new-game-button-border',
				themeStyles.colors.newGameButtonBorder
			);
			root.style.setProperty(
				'--game-over-bg',
				`${themeStyles.colors.background}dd`
			);
			root.style.setProperty('--game-over-text', themeStyles.colors.title);
		}
	}, [themeStyles]);

	const handleNewGame = () => {
		setScore(0);
		// Перезагружаем страницу для новой игры
		window.location.reload();
	};

	const handleScoreUpdate = useCallback(
		(newScore: number) => {
			setScore(newScore);
			if (newScore > bestScore) {
				setBestScore(newScore);
				if (typeof window !== 'undefined') {
					localStorage.setItem('bestScore', newScore.toString());
				}
			}
		},
		[bestScore]
	);

	return (
		<>
			<Head>
				<title>2048 NextJs</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Board
					isClient={isClient}
					onScoreUpdate={handleScoreUpdate}
					currentTheme={currentTheme}
				/>
				<RightPanel
					score={score}
					bestScore={bestScore}
					onNewGame={handleNewGame}
					currentTheme={currentTheme}
				/>
				<ThemeSelector
					currentTheme={currentTheme}
					onThemeChange={changeTheme}
				/>
			</main>
		</>
	);
}
